version: '3'
services:

  backend:
    build: .
    container_name: data-in-cloud-app
    depends_on:
      - postgres
    ports:
      - "8087:8080"

  postgres:
    image: "postgres:14.11"
    container_name: postgres-database
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=DataInCloud
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - HOST_URL=host.docker.internal
