spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/DataInCloud
    username: postgres
    password: password

  data:
    mongodb:
      authenticationDatabase: admin
      host: mongo
      port: 27017
      username: user
      password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: host.docker.internal
    virtual-host: vhost
    username: user
    password: password

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  error:
    include-message: always